exit_after_plane: 1
exit_if_no_prior: false
prior_exit_plane: null
priority:
  prior_envir:
  - 银金彩
  - 彩虹时代
  - 黄金时代
  envir_1:
  - 蓝海
  - 头彩
  - 白银时代
  - 三星佩佩
  - 粗星佩佩
  - 劳务派遣合同
  - 尾彩
  envir_2:
  - 专家研讨会
  - 特邀专家：停云
  - 特邀专家：加拉赫
  - 特邀专家：银狼
  - 特邀专家：桑博
  - 火药味
  - 特权阶级
  - 增发货币
  - 人才引进
  - 红钻贵族
  - 蓝钻贵族
  - 英雄登场
  - 战力提升
  - 战力飙升
  - 人才储备
  - 进化算法
  envir_3:
  - 追击概念股
  - 染血概念股
  - 能量概念股
  - 列车同行概念股
  - 银河学者概念股
  - 贝洛伯格概念股
  - 星间旅人概念股
  - 仙舟概念股
  - 狼狩概念股
  - 昼之半神概念股
  - 夜之半神概念股
  - 击破概念股
  - 群攻概念股
  - 减益概念股
  - 战技点概念股
  - 列车同行邀请
  - 银河学者邀请
  - 贝洛伯格邀请
  - 星间旅人邀请
  - 仙舟邀请
  - 狼狩邀请
  - 盛会之星邀请
  - 昼之半神邀请
  - 夜之半神邀请
  - 追击邀请
  - 击破邀请
  - 群攻邀请
  - 能量邀请
  - 燃血邀请
  - 减益邀请
  - 持续伤害邀请
  - 量子同频邀请
  - 战技点邀请
  - 欢愉邀请
  - 命运圣杯邀请
  - 量子同频契约
  - 公司契约
  - 持续伤害契约
  - 战技点契约
  - 星核猎手契约
  - 欢愉契约
  - 命运圣杯契约
  envir_4:
  - 深井角斗场
  - 经济过热
  - 二手市场
  - 人身意外险
  - 过剩经费
  - 轮岗
  - 战争边疆
  - 经济严重过热
  - 长线利好
  - 人才下沉
  - 联席决策
  - 命运礼物
  - 成功经验
  - 敌后破坏
  - 策略大师
